# Generated by Django 4.0 on 2022-02-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_choice_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
        migrations.AlterModelTable(
            name='poll',
            table='polls',
        ),
    ]
