# Generated by Django 4.0 on 2022-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_choice_options_alter_poll_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='option_text',
            field=models.TextField(default='yesyeas', max_length=2000, verbose_name='Текст варианта'),
            preserve_default=False,
        ),
    ]
